using UnityEditor;
using System.IO;
using System.Text;
using System.Collections.Generic;

namespace vanhaodev.soundmanager
{
	[InitializeOnLoad]
	public static class SoundChannelGenerator
	{
		private const string FOLDER = "Assets/Generated/com.vanhaodev.soundmanager";
		private const string FILE_NAME = "SoundChannelType.cs";
		private const string PATH = FOLDER + "/" + FILE_NAME;

		static SoundChannelGenerator()
		{
			EditorApplication.delayCall += Init;
		}

		private static void Init()
		{
			if (File.Exists(PATH))
				return;

			string[] defaultChannels = CreateDefaultChannels(24);
			GenerateEnum(defaultChannels);

			UnityEngine.Debug.Log("[SoundManager] Auto generated SoundChannelType");
		}

		// =========================
		// CORE
		// =========================

		public static void GenerateEnum(string[] channelNames)
		{
			if (!Directory.Exists(FOLDER))
			{
				Directory.CreateDirectory(FOLDER);
			}

			string path = Path.Combine(FOLDER, FILE_NAME);

			var sb = new StringBuilder();

			sb.AppendLine("namespace vanhaodev.soundmanager");
			sb.AppendLine("{");
			sb.AppendLine("\t/*");
			sb.AppendLine("\t * WARNING: This file is auto-generated.");
			sb.AppendLine("\t * Do NOT edit this file manually.");
			sb.AppendLine("\t * Use: Tools -> Sound Manager -> Channel Settings");
			sb.AppendLine("\t */");
			sb.AppendLine("\tpublic enum SoundChannelType");
			sb.AppendLine("\t{");

			var used = new HashSet<string>();

			for (int i = 0; i < channelNames.Length; i++)
			{
				string name = Sanitize(channelNames[i]);

				string original = name;
				int suffix = 1;
				while (used.Contains(name))
				{
					name = original + suffix;
					suffix++;
				}

				used.Add(name);

				sb.AppendLine($"\t\t{name} = {i},");
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");

			string newContent = sb.ToString();

			if (File.Exists(path))
			{
				string oldContent = File.ReadAllText(path);
				if (oldContent == newContent)
					return;
			}

			File.WriteAllText(path, newContent);
			AssetDatabase.Refresh();
		}

		// =========================
		// HELPERS
		// =========================

		private static string[] CreateDefaultChannels(int count)
		{
			var result = new string[count];
			for (int i = 0; i < count; i++)
			{
				result[i] = $"Channel{i}";
			}
			return result;
		}

		private static string Sanitize(string name)
		{
			var sb = new StringBuilder();

			foreach (char c in name)
			{
				if (char.IsLetterOrDigit(c))
				{
					sb.Append(c);
				}
			}

			string result = sb.ToString();

			if (string.IsNullOrEmpty(result))
			{
				result = "Channel";
			}

			if (char.IsDigit(result[0]))
			{
				result = "_" + result;
			}

			return result;
		}
	}
}